/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package student_enrollment_system_v2;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JPanel;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author river
 */
public final class Registry extends javax.swing.JDialog {

    private int ter;
    private int con;
    int Id;
    int counter;
    private JPanel jpanel;
    private JPanel jpanel2;
    StudentCRUD SC = new StudentCRUD();
    StudentInfo S = new StudentInfo();
    CourseInfo ci = new CourseInfo();
    CourseCRUD cc = new CourseCRUD();

    public Registry(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        StudentComboBox();
        CourseComboBox();

    }

    public void setjpanel(JPanel jpanel) {
        this.jpanel = jpanel;
    }

    public void setJpanel2(JPanel jpanel2) {
        this.jpanel2 = jpanel2;
    }

    public void setTer(int ter) {
        this.ter = ter;
    }

    public void setCon(int con) {
        this.con = con;
        java.awt.Container parent = this.getContentPane();
        java.awt.CardLayout layout = (java.awt.CardLayout) parent.getLayout();
        if (this.con == 1) {
            layout.show(parent, "card3");
            this.con = 0;
        } else if (this.con == 2) {
            layout.show(parent, "card4");
            this.con = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 250));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("First Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(85, 40, 75, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Last Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(87, 80, 73, 30);

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(160, 40, 140, 30);

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(160, 80, 140, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Age:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 120, 30, 30);

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(160, 120, 140, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 160, 40, 30);

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(160, 160, 140, 30);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 210, 79, 27);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(220, 210, 76, 27);

        getContentPane().add(jPanel1, "card2");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 250));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Course Name:");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Course Description:");

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Credits:");

        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ok");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField6)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, "card3");

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(90, 70, 210, 26);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Student Name");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(147, 50, 100, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(90, 140, 210, 26);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Course");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(170, 120, 50, 20);

        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(80, 200, 76, 27);

        jButton6.setText("OK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(230, 200, 76, 27);

        getContentPane().add(jPanel3, "card4");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void set() {
        if (ter == 0) {
            try (Connection conn = DBConnection.getConnection()) {
                String Sql = "SELECT * FROM mydb.`student Table` WHERE `Student Id` = ?";
                PreparedStatement stmt = conn.prepareStatement(Sql);
                stmt.setInt(1, Id);
                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    String fName = rs.getString("First_Name");
                    String lName = rs.getString("Last_Name");
                    int age = rs.getInt("Age");
                    String email = rs.getString("Email");
                    jTextField2.setText(fName);
                    jTextField3.setText(lName);
                    jTextField4.setText(String.valueOf(age));
                    jTextField5.setText(email);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else if (ter == 1) {
            try (Connection conn = DBConnection.getConnection()) {
                String Sql = "SELECT * FROM mydb.`course table` WHERE `Course_ID` = ?";
                PreparedStatement stmt = conn.prepareStatement(Sql);
                stmt.setInt(1, Id);
                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    String CName = rs.getString("Course_Name");
                    String Cd = rs.getString("Course_Description");
                    int credits = rs.getInt("Credits");
                    jTextField1.setText(CName);
                    jTextField6.setText(Cd);
                    jTextField7.setText(String.valueOf(credits));
                    ter = 0;
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                ter = 0;
            }
        }
    }

    public void StudentComboBox() {
        jComboBox1.removeAllItems();

        String url = "jdbc:mysql://127.0.0.1:3306/?user=root";
        String user = "root";
        String password = "MJ091406";
        String sql = "SELECT `student Id`, `First_Name`,`Last_Name` FROM mydb.`Student table`";

        try (Connection conn = DriverManager.getConnection(url, user, password); PreparedStatement stmt = conn.prepareStatement(sql); ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                int id = rs.getInt("student Id");
                String fname = rs.getString("First_Name");
                String lname = rs.getString("Last_Name");

                jComboBox1.addItem(Integer.toString(id) + " - " + fname + " " + lname);
            }

        } catch (SQLException e) {
            System.err.println("Database error while loading students:");
            e.printStackTrace();

        }
        jComboBox1.setSelectedIndex(-1);
    }

    public void CourseComboBox() {
        jComboBox2.removeAllItems();

        String url = "jdbc:mysql://127.0.0.1:3306/?user=root";
        String user = "root";
        String password = "MJ091406";
        String sql = "SELECT `Course_ID`, `Course_Name` FROM mydb.`Course table`";

        try (Connection conn = DriverManager.getConnection(url, user, password); PreparedStatement stmt = conn.prepareStatement(sql); ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                int id = rs.getInt("Course_ID");
                String cname = rs.getString("Course_Name");

                jComboBox2.addItem(Integer.toString(id) + " - " + cname + " ");
            }

        } catch (SQLException e) {
            System.err.println("Database error while loading students:");
            e.printStackTrace();

        }
        jComboBox2.setSelectedIndex(-1);
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String input1 = jTextField2.getText();
        String input2 = jTextField3.getText();
        String input3 = jTextField4.getText();
        String input4 = jTextField5.getText();
        if (input1 != null && !input1.trim().isEmpty()) {
            if (input1.matches("^[a-zA-Z\\s]+$")) {
                if (input2 != null && !input2.trim().isEmpty()) {
                    if (input2.matches("^[a-zA-Z\\s]+$")) {
                        if (input3 != null && !input3.trim().isEmpty()) {
                            try {
                                int Value = Integer.parseInt(input3.trim());
                                if (input4 != null && !input4.trim().isEmpty()) {
                                    if (counter == 0) {
                                        S.setFirst_Name(input1);
                                        S.setLast_Name(input2);
                                        S.setAge(Value);
                                        S.setEmail(input4);
                                        SC.addStudent(S);
                                        jTextField2.setText("");
                                        jTextField3.setText("");
                                        jTextField4.setText("");
                                        jTextField5.setText("");
                                    } else if (counter == 1) {
                                        StudentInfo st = new StudentInfo();
                                        StudentCRUD sc = new StudentCRUD();
                                        st.setFirst_Name(input1);
                                        st.setLast_Name(input2);
                                        st.setAge(Value);
                                        st.setEmail(input4);
                                        st.setStudent_ID(Id);
                                        sc.updateStudent(st);
                                        jTextField2.setText("");
                                        jTextField3.setText("");
                                        jTextField4.setText("");
                                        jTextField5.setText("");
                                        counter = 0;
                                        this.dispose();
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(this,
                                            "This field cannot be empty.",
                                            "Empty Field",
                                            JOptionPane.WARNING_MESSAGE);
                                }
                            } catch (NumberFormatException e) {
                                JOptionPane.showMessageDialog(this,
                                        "Please enter a valid number (e.g., 3, or 3.5).",
                                        "Invalid Input",
                                        JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this,
                                    "This field cannot be empty.",
                                    "Empty Field",
                                    JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "Please enter letters only. Numbers and special characters are not allowed.",
                                "Invalid Input",
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "This field cannot be empty.",
                            "Empty Field",
                            JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "Please enter letters only. Numbers and special characters are not allowed.",
                        "Invalid Input",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "This field cannot be empty.",
                    "Empty Field",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jpanel.setBackground(new Color(204, 204, 204));
        jpanel2.setBackground(Color.blue);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jpanel.setBackground(new Color(204, 204, 204));
        jpanel2.setBackground(Color.blue);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String input = jTextField1.getText();
        String input2 = jTextField6.getText();
        String input3 = jTextField7.getText();
        if (input != null && !input.trim().isEmpty()) {
            if (input2 != null && !input2.trim().isEmpty()) {
                if (input3 != null && !input3.trim().isEmpty()) {
                    try {
                        double Value = Double.parseDouble(input3.trim());
                        if (counter == 0) {
                            ci.setCourseName(input);
                            ci.setCourseDetails(input2);
                            ci.setCredits(Value);
                            cc.addCourse(ci);
                            jTextField1.setText("");
                            jTextField6.setText("");
                            jTextField7.setText("");
                        } else if (counter == 1) {
                            CourseInfo ci = new CourseInfo();
                            CourseCRUD cc = new CourseCRUD();
                            ci.setCourseName(input);
                            ci.setCourseDetails(input2);
                            ci.setCredits(Value);
                            ci.setCourseid(Id);
                            cc.updateCourse(ci);
                            jTextField1.setText("");
                            jTextField6.setText("");
                            jTextField7.setText("");
                            jpanel.setBackground(new Color(204, 204, 204));
                            jpanel2.setBackground(Color.blue);
                            counter = 0;
                            this.dispose();
                        }
                    } catch (NumberFormatException e) {
                        // 3. Catch it if they typed letters instead of a decimal number
                        JOptionPane.showMessageDialog(this,
                                "Please enter a valid number (e.g., 3, or 3.5).",
                                "Invalid Input",
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "This field cannot be empty.",
                            "Empty Field",
                            JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "This field cannot be empty.",
                        "Empty Field",
                        JOptionPane.WARNING_MESSAGE);
            }

        } else {
            // 4. Warn them if they left it blank
            JOptionPane.showMessageDialog(this,
                    "This field cannot be empty.",
                    "Empty Field",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jComboBox1.getSelectedIndex() == -1 || jComboBox2.getSelectedIndex() == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select both a student and a course.", "Missing Information", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String selectedStudentStr = jComboBox1.getSelectedItem().toString();
    String selectedCourseStr = jComboBox2.getSelectedItem().toString();

    int actualStudentId = Integer.parseInt(selectedStudentStr.split("-")[0].trim());
    int actualCourseId = Integer.parseInt(selectedCourseStr.split("-")[0].trim());

    EnrollmentCRUD ec = new EnrollmentCRUD();

    if (ec.isAlreadyEnrolled(actualStudentId, actualCourseId)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Enrollment Failed: This student is already enrolled in this course.", "Duplicate Enrollment", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!ec.isProgramAllowed(actualStudentId, actualCourseId)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Enrollment Denied! This student belongs to a different program track based on their active courses.", "Program Mismatch", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    java.time.LocalDateTime rightNow = java.time.LocalDateTime.now();
    EnrollmentInfo e = new EnrollmentInfo();

    e.setStudentID(actualStudentId);
    e.setCourseID(actualCourseId);
    e.setDate(rightNow);

    ec.addEnrollment(e);
    
    javax.swing.JOptionPane.showMessageDialog(this, "Student successfully enrolled!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    jComboBox1.setSelectedIndex(-1);
    jComboBox2.setSelectedIndex(-1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jpanel.setBackground(new Color(204, 204, 204));
        jpanel2.setBackground(Color.blue);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Registry dialog = new Registry(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
