/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_enrollment_system_v2;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author river
 */
public class StudentGUI extends javax.swing.JFrame {

    private int step = 0;
    private Timer timer;
    public StudentGUI() {
        initComponents();
        animation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setVerifyInputWhenFocusTarget(false);
        jPanel11.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new Color(255,255,255,200));
        jPanel3.setLayout(null);

        jPanel5.setBackground(java.awt.Color.blue);
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 70));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Home");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(50, 0, 60, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeTab.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(50, 0, 60, 90);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 0, 150, 70);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.setMaximumSize(new java.awt.Dimension(150, 70));
        jPanel6.setMinimumSize(new java.awt.Dimension(150, 70));
        jPanel6.setPreferredSize(new java.awt.Dimension(150, 70));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UpdateTab.png"))); // NOI18N
        jPanel6.add(jLabel14);
        jLabel14.setBounds(0, 10, 70, 50);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Update");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(30, 20, 70, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UpdateTab.png"))); // NOI18N
        jPanel6.add(jLabel10);
        jLabel10.setBounds(0, 10, 100, 50);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(0, 140, 150, 70);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.setMaximumSize(new java.awt.Dimension(150, 70));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistry.png"))); // NOI18N
        jPanel4.add(jLabel15);
        jLabel15.setBounds(60, 0, 20, 70);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Student Registry");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 10, 150, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentRegistry.png"))); // NOI18N
        jPanel4.add(jLabel7);
        jLabel7.setBounds(60, 0, 50, 70);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 70, 150, 70);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.setMinimumSize(new java.awt.Dimension(150, 70));
        jPanel7.setPreferredSize(new java.awt.Dimension(150, 70));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Delete");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(40, 10, 70, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TrashTab.png"))); // NOI18N
        jPanel7.add(jLabel12);
        jLabel12.setBounds(0, 0, 101, 70);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(0, 210, 150, 70);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("           View");
        jPanel8.add(jLabel17);
        jLabel17.setBounds(0, 40, 150, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ViewTab.png"))); // NOI18N
        jPanel8.add(jLabel16);
        jLabel16.setBounds(0, -20, 150, 90);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(0, 280, 150, 70);

        jPanel13.setBackground(java.awt.Color.blue);
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });
        jPanel13.setLayout(null);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursewindow.png"))); // NOI18N
        jPanel13.add(jLabel43);
        jLabel43.setBounds(2, 2, 150, 50);

        jPanel3.add(jPanel13);
        jPanel13.setBounds(0, 350, 150, 50);

        jPanel14.setBackground(java.awt.Color.blue);
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(null);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollment Window.png"))); // NOI18N
        jPanel14.add(jLabel44);
        jLabel44.setBounds(0, 10, 150, 30);

        jPanel3.add(jPanel14);
        jPanel14.setBounds(0, 400, 150, 0);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 30, 150, 450);

        jPanel10.setBackground(new Color(204,255,255,128));
        jPanel10.setLayout(null);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        jPanel10.add(jLabel19);
        jLabel19.setBounds(90, -20, 510, 420);

        jLabel2.setBackground(new Color(255,255,255,0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("E");
        jPanel10.add(jLabel2);
        jLabel2.setBounds(200, 260, 13, 160);

        jLabel3.setBackground(new Color(255,255,255,0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("L");
        jPanel10.add(jLabel3);
        jLabel3.setBounds(240, 320, 12, 100);

        jLabel4.setBackground(new Color(255,255,255,0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("C");
        jPanel10.add(jLabel4);
        jLabel4.setBounds(290, 350, 15, 100);

        jLabel20.setBackground(new Color(255,255,255,0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("M");
        jPanel10.add(jLabel20);
        jLabel20.setBounds(390, 210, 23, 250);

        jLabel1.setBackground(new Color(0,0,0,255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("W");
        jPanel10.add(jLabel1);
        jLabel1.setBounds(160, 190, 24, 230);

        jLabel21.setBackground(new Color(255,255,255,0));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("E");
        jPanel10.add(jLabel21);
        jLabel21.setBounds(440, 170, 13, 250);

        jLabel5.setBackground(new Color(255,255,255,0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("O");
        jPanel10.add(jLabel5);
        jLabel5.setBounds(340, 300, 18, 140);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel2);
        jPanel2.setBounds(140, 0, 330, 450);

        jPanel1.add(jPanel10);
        jPanel10.setBounds(150, 30, 700, 450);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroun2.0.png"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(0, 0, 850, 510);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(0, 0, 860, 30);

        jPanel11.add(jPanel1, "card2");

        jPanel12.setBackground(new java.awt.Color(153, 255, 255));
        jPanel12.setLayout(null);

        jPanel16.setBackground(new Color(255,255,255,200));
        jPanel16.setLayout(null);

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17MouseClicked(evt);
            }
        });
        jPanel17.setLayout(null);

        jLabel25.setBackground(new Color(0,0,0,180));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addcourse tab.png"))); // NOI18N
        jPanel17.add(jLabel25);
        jLabel25.setBounds(30, 10, 20, 50);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new Color(0,0,0,255));
        jLabel26.setText("ADD COURSE");
        jPanel17.add(jLabel26);
        jLabel26.setBounds(20, 20, 100, 20);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addcourse tab.png"))); // NOI18N
        jPanel17.add(jLabel27);
        jLabel27.setBounds(30, 10, 70, 50);

        jPanel16.add(jPanel17);
        jPanel17.setBounds(0, 70, 150, 70);

        jPanel18.setBackground(new java.awt.Color(204, 204, 204));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18MouseClicked(evt);
            }
        });
        jPanel18.setLayout(null);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UpdateTab.png"))); // NOI18N
        jPanel18.add(jLabel31);
        jLabel31.setBounds(0, 0, 70, 80);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Update ");
        jPanel18.add(jLabel30);
        jLabel30.setBounds(40, 10, 70, 50);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UpdateTab.png"))); // NOI18N
        jLabel29.setText("jLabel29");
        jPanel18.add(jLabel29);
        jLabel29.setBounds(0, 0, 150, 80);

        jPanel16.add(jPanel18);
        jPanel18.setBounds(0, 140, 150, 80);

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel19MouseClicked(evt);
            }
        });
        jPanel19.setLayout(null);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TrashTab.png"))); // NOI18N
        jPanel19.add(jLabel32);
        jLabel32.setBounds(0, 0, 70, 70);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Delete");
        jPanel19.add(jLabel36);
        jLabel36.setBounds(40, 30, 80, 25);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TrashTab.png"))); // NOI18N
        jPanel19.add(jLabel37);
        jLabel37.setBounds(0, 0, 150, 70);

        jPanel16.add(jPanel19);
        jPanel19.setBounds(0, 220, 150, 70);

        jPanel20.setBackground(new java.awt.Color(204, 204, 204));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel20MouseClicked(evt);
            }
        });
        jPanel20.setLayout(null);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("View");
        jPanel20.add(jLabel38);
        jLabel38.setBounds(50, 40, 50, 20);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ViewTab.png"))); // NOI18N
        jPanel20.add(jLabel33);
        jLabel33.setBounds(0, 10, 150, 40);

        jPanel16.add(jPanel20);
        jPanel20.setBounds(0, 290, 150, 70);

        jPanel22.setBackground(java.awt.Color.blue);
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel22MouseClicked(evt);
            }
        });

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student Window.png"))); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel16.add(jPanel22);
        jPanel22.setBounds(0, 360, 150, 50);

        jPanel23.setBackground(java.awt.Color.blue);
        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel23MouseClicked(evt);
            }
        });

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enrollment Window.png"))); // NOI18N

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel16.add(jPanel23);
        jPanel23.setBounds(0, 410, 150, 50);

        jPanel31.setBackground(java.awt.Color.blue);
        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel31.setLayout(null);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeTab.png"))); // NOI18N
        jPanel31.add(jLabel23);
        jLabel23.setBounds(0, 0, 150, 70);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Home");
        jPanel31.add(jLabel24);
        jLabel24.setBounds(70, 20, 60, 30);

        jPanel16.add(jPanel31);
        jPanel31.setBounds(0, 0, 150, 70);

        jPanel12.add(jPanel16);
        jPanel16.setBounds(0, 30, 150, 450);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel21);
        jPanel21.setBounds(0, 0, 860, 30);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Enrollment logo.png"))); // NOI18N
        jPanel12.add(jLabel22);
        jLabel22.setBounds(150, 20, 700, 460);

        jPanel33.setBackground(new Color(255,255,255,200));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel33);
        jPanel33.setBounds(0, 30, 860, 460);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroun2.0.png"))); // NOI18N
        jPanel12.add(jLabel28);
        jLabel28.setBounds(3, 10, 854, 490);

        jPanel11.add(jPanel12, "card3");

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(null);

        jPanel24.setBackground(new java.awt.Color(153, 255, 255));
        jPanel24.setLayout(null);

        jPanel34.setBackground(new Color(255,255,255,128));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/course background.png"))); // NOI18N

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel24.add(jPanel34);
        jPanel34.setBounds(150, 0, 710, 460);

        jPanel25.setBackground(new Color(255,255,255,200));
        jPanel25.setLayout(null);

        jPanel26.setBackground(new java.awt.Color(204, 204, 204));
        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel26MouseClicked(evt);
            }
        });
        jPanel26.setLayout(null);

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Enrollment");
        jPanel26.add(jLabel50);
        jLabel50.setBounds(40, 40, 90, 22);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add enrollment.png"))); // NOI18N
        jPanel26.add(jLabel40);
        jLabel40.setBounds(-30, 10, 100, 60);

        jPanel25.add(jPanel26);
        jPanel26.setBounds(0, 80, 150, 80);

        jPanel27.setBackground(new java.awt.Color(204, 204, 204));
        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel27MouseClicked(evt);
            }
        });
        jPanel27.setLayout(null);

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("Delete");
        jPanel27.add(jLabel51);
        jLabel51.setBounds(50, 50, 70, 25);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TrashTab.png"))); // NOI18N
        jPanel27.add(jLabel41);
        jLabel41.setBounds(2, 8, 146, 50);

        jPanel25.add(jPanel27);
        jPanel27.setBounds(0, 160, 150, 80);

        jPanel28.setBackground(new java.awt.Color(204, 204, 204));
        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel28MouseClicked(evt);
            }
        });
        jPanel28.setLayout(null);

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("View");
        jPanel28.add(jLabel52);
        jLabel52.setBounds(50, 45, 60, 30);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ViewTab.png"))); // NOI18N
        jLabel42.setText("jLabel42");
        jPanel28.add(jLabel42);
        jLabel42.setBounds(0, 0, 150, 60);

        jPanel25.add(jPanel28);
        jPanel28.setBounds(0, 240, 150, 80);

        jPanel29.setBackground(java.awt.Color.blue);
        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel29MouseClicked(evt);
            }
        });

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student Window.png"))); // NOI18N

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel25.add(jPanel29);
        jPanel29.setBounds(0, 350, 150, 50);

        jPanel30.setBackground(java.awt.Color.blue);
        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel30MouseClicked(evt);
            }
        });

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursewindow.png"))); // NOI18N

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel25.add(jPanel30);
        jPanel30.setBounds(0, 400, 150, 50);

        jPanel32.setBackground(java.awt.Color.blue);
        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel32.setLayout(null);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Home");
        jPanel32.add(jLabel49);
        jLabel49.setBounds(70, 30, 60, 25);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeTab.png"))); // NOI18N
        jPanel32.add(jLabel39);
        jLabel39.setBounds(2, 2, 150, 76);

        jPanel25.add(jPanel32);
        jPanel32.setBounds(0, 0, 150, 80);

        jPanel24.add(jPanel25);
        jPanel25.setBounds(0, 0, 150, 460);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroun2.0.png"))); // NOI18N
        jPanel24.add(jLabel34);
        jLabel34.setBounds(0, -10, 860, 470);

        jPanel15.add(jPanel24);
        jPanel24.setBounds(0, 30, 860, 450);

        jPanel11.add(jPanel15, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        Registry R = new Registry(this, true);
        jPanel5.setBackground(new Color(204, 204, 204));
        jPanel6.setBackground(new Color(204, 204, 204));
        jPanel7.setBackground(new Color(204, 204, 204));
        jPanel8.setBackground(new Color(204, 204, 204));
        jPanel4.setBackground(Color.blue);
        R.setjpanel(this.jPanel4);
        R.setJpanel2(this.jPanel5);
        R.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        StudentID st = new StudentID(this,true);
        jPanel5.setBackground(new Color(204, 204, 204));
        jPanel7.setBackground(new Color(204, 204, 204));
        jPanel8.setBackground(new Color(204, 204, 204));
        jPanel4.setBackground(new Color(204, 204, 204)); 
        jPanel6.setBackground(Color.blue);
        st.setJpanel(jPanel6);
        st.setJpanel2(jPanel5); 
        st.setVisible(true);
        
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        StudentID st = new StudentID(this,true);
        st.counter++;
        jPanel5.setBackground(new Color(204, 204, 204));
        jPanel6.setBackground(new Color(204, 204, 204));
        jPanel8.setBackground(new Color(204, 204, 204));
        jPanel4.setBackground(new Color(204, 204, 204)); 
        jPanel7.setBackground(Color.blue);
        st.setJpanel(jPanel7);
        st.setJpanel2(jPanel5);
        st.setVisible(true);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        list l = new list(this,true);
        jPanel5.setBackground(new Color(204, 204, 204));
        jPanel6.setBackground(new Color(204, 204, 204));
        jPanel7.setBackground(new Color(204, 204, 204));
        jPanel4.setBackground(new Color(204, 204, 204)); 
        jPanel8.setBackground(Color.blue);
        l.setjpanel4(jPanel8);
        l.setjpanel5(jPanel5);
        l.setVisible(true);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        jPanel12.setVisible(true);
        jPanel1.setVisible(false);
        timer.stop();
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        jPanel15.setVisible(true);
        timer.stop();
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jPanel14MouseClicked

    private void jPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseClicked
        Registry R = new Registry(this,true);
        jPanel31.setBackground(new Color(204, 204, 204));
        jPanel17.setBackground(Color.blue);
        R.setCon(1);
        R.setjpanel(this.jPanel17);
        R.setJpanel2(this.jPanel31);
        R.setVisible(true);
    }//GEN-LAST:event_jPanel17MouseClicked

    private void jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseClicked
        StudentID s = new StudentID(this,true);
        Registry r = new Registry(this,true);
        jPanel31.setBackground(new Color(204, 204, 204));
        jPanel18.setBackground(Color.blue);
        s.setCon(1);
        s.setJpanel(jPanel18);
        s.setJpanel2(jPanel31);
        r.setjpanel(jPanel17);
        r.setJpanel2(jPanel31);
        s.setVisible(true);
    }//GEN-LAST:event_jPanel18MouseClicked

    private void jPanel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseClicked
        StudentID s = new StudentID(this,true);
        jPanel31.setBackground(new Color(204, 204, 204));
        jPanel19.setBackground(Color.blue);
        s.counter++;
        s.setCon(1);
        s.setJpanel(this.jPanel19);
        s.setJpanel2(jPanel31);
        s.setVisible(true);
    }//GEN-LAST:event_jPanel19MouseClicked

    private void jPanel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseClicked
        list l = new list(this,true);
        jPanel31.setBackground(new Color(204, 204, 204));
        jPanel20.setBackground(Color.blue);
        l.setCon(1);
        l.setCounter(1);
        l.setjpanel4(this.jPanel20);
        l.setjpanel5(this.jPanel31);
        l.setVisible(true);
    }//GEN-LAST:event_jPanel20MouseClicked

    private void jPanel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel22MouseClicked
        jPanel1.setVisible(true);
        timer.start();
        jPanel12.setVisible(false);
    }//GEN-LAST:event_jPanel22MouseClicked

    private void jPanel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel26MouseClicked
        Registry R = new Registry(this,true);
        jPanel26.setBackground(Color.blue);
        jPanel32.setBackground(new Color(204, 204, 204));
        R.setCon(2);
        R.setjpanel(jPanel26);
        R.setJpanel2(jPanel32);
        R.setVisible(true);
    }//GEN-LAST:event_jPanel26MouseClicked

    private void jPanel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel28MouseClicked
        list l = new list(this,true);
        jPanel28.setBackground(Color.blue);
        jPanel32.setBackground(new Color(204, 204, 204));
        l.setCounter(2);
        l.setjpanel4(jPanel28);
        l.setjpanel5(jPanel32);
        l.setVisible(true);
    }//GEN-LAST:event_jPanel28MouseClicked

    private void jPanel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel27MouseClicked
        StudentID S = new StudentID(this,true);
        jPanel27.setBackground(Color.blue);
        jPanel32.setBackground(new Color(204, 204, 204));
        S.setCon(2);
        S.setJpanel(jPanel27);
        S.setJpanel2(jPanel32);
        S.setVisible(true);
    }//GEN-LAST:event_jPanel27MouseClicked

    private void jPanel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel29MouseClicked
        timer.start();
        jPanel1.setVisible(true);
        jPanel15.setVisible(false);
    }//GEN-LAST:event_jPanel29MouseClicked

    private void jPanel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel30MouseClicked
        jPanel15.setVisible(false);
        jPanel12.setVisible(true);
    }//GEN-LAST:event_jPanel30MouseClicked

    private void jPanel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel23MouseClicked
        jPanel12.setVisible(false);
        jPanel15.setVisible(true);
    }//GEN-LAST:event_jPanel23MouseClicked
    public void animation() {
          timer = new Timer(500, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                switch (step) {
                    case 0:
                        jLabel1.setForeground(Color.red);
                        step++;
                        break;
                    case 1:
                        jLabel2.setForeground(Color.red);
                        step++;
                        break;
                    case 2:
                        jLabel3.setForeground(Color.red);
                        step++;
                        break;
                    case 3:
                        jLabel4.setForeground(Color.red);
                        step++;
                        break;
                    case 4:
                        jLabel5.setForeground(Color.red);
                        step++;
                        break;
                    case 5:
                        jLabel20.setForeground(Color.red);
                        step++;
                        break;
                    case 6:
                        jLabel21.setForeground(Color.red);
                        step++;
                        break;
                    case 7:
                        jLabel1.setForeground(Color.black);
                        jLabel2.setForeground(Color.black);
                        jLabel3.setForeground(Color.black);
                        jLabel4.setForeground(Color.black);
                        jLabel5.setForeground(Color.black);
                        jLabel20.setForeground(Color.black);
                        jLabel21.setForeground(Color.black);
                        step = 0;
                        break;
                }
            }
        });

        timer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
